### ISSUE TITLE
POST times out after 15s

### ISSUE THREAD

**Issue by kaihendry** [unee-t/unit#10]
The SQL needs to run faster. This is happening despite an upgrade to **db.r4.xlarge**!
```
[hendry@t480s unit]$ up logs error
  Apr 18th 10:13:53am ERRO production 0b4def0 response: duration=15.002s id=8cad019a-617f-11e9-a574-93a4c016c0a9 ip=3.0.200.215 method=POST path=/create size=0 B status=502
  Apr 18th 10:13:53am ERRO production 0b4def0 response: duration=15.001s id=8ca38c8c-617f-11e9-b34a-47ccbeca6aab ip=13.229.200.180 method=POST path=/create size=0 B status=502
  Apr 18th 10:13:54am ERRO production 0b4def0 response: duration=15.001s id=8dbee791-617f-11e9-b857-73d61e560022 ip=3.0.200.215 method=POST path=/create size=0 B status=502
  Apr 18th 10:13:54am ERRO production 0b4def0 response: duration=15.001s id=8d709fd7-617f-11e9-b16b-1f9f98ea4448 ip=3.0.200.215 method=POST path=/create size=0 B status=502
  Apr 18th 10:13:54am ERRO production 0b4def0 response: duration=15.001s id=8de9a09c-617f-11e9-854b-877d224f23a3 ip=3.0.200.215 method=POST path=/create size=0 B status=502
  Apr 18th 10:13:54am ERRO production 0b4def0 response: duration=15.002s id=8dd7513b-617f-11e9-9b23-5da467f97222 ip=3.0.200.215 method=POST path=/create size=0 B status=502
  Apr 18th 10:13:54am ERRO production 0b4def0 response: duration=15.001s id=8dcaf4c0-617f-11e9-a9a1-73c8784e424a ip=13.229.200.180 method=POST path=/create size=0 B status=502
  Apr 18th 10:14:06am ERRO production 0b4def0 response: duration=15.002s id=8d205d19-617f-11e9-8b0d-f7d7ab7356f4 ip=13.229.200.180 method=POST path=/create size=0 B status=502
  Apr 18th 10:14:06am ERRO production 0b4def0 response: duration=15.002s id=8d1894fb-617f-11e9-a26e-6b9f72f22566 ip=3.0.200.215 method=POST path=/create size=0 B status=502
  Apr 18th 10:14:06am ERRO production 0b4def0 response: duration=15.001s id=8d3b5f52-617f-11e9-a453-ed2ae5a3caa4 ip=13.229.200.180 method=POST path=/create size=0 B status=502
  Apr 18th 10:24:44am ERRO production 0b4def0 [mysql] 2019/04/18 02:24:44 packets.go:112: closing bad idle connection: EOF
  Apr 18th 10:24:44am ERRO production 0b4def0 [mysql] 2019/04/18 02:24:44 packets.go:112: closing bad idle connection: EOF
  Apr 18th 10:38:40am ERRO production 0b4def0 [mysql] 2019/04/18 02:38:40 packets.go:112: closing bad idle connection: EOF
  Apr 18th 11:00:35am ERRO production 0b4def0 [mysql] 2019/04/18 03:00:35 packets.go:112: closing bad idle connection: EOF
```

**Comment by franck-boullier** [comment]
> The SQL needs to run faster.

This is unlikely to happen in the foreseeable future ---> we need to find a different way so we can live with how fast the queries are today

**Comment by kaihendry** [comment]
* ~~higher instance type~~
* ~~longer time out~~
* SQL optimization
* make it async / create a queue - makes it very complex and unit creation isn't immediate

**Comment by franck-boullier** [comment]
* ~~higher instance type~~
* ~~longer time out~~
* ~~SQL optimization~~
* make it async / create a queue - makes it very complex and unit creation isn't immediate <--- *only possible option as of today. Will become fast if and when we manage to get the SQL process faster. Most future proof solution. Most resilient solution*

**Comment by franck-boullier** [comment]
The main reasons/arguments for async are that 

- We have long-running operations (create a unit) that do not require to block the execution of everything else.
- We need to perform other work while waiting for the result from the long running task.
- Trying to do the unit creation in a synchronous way is breaking the system (units are not created as they should be ---> we might be creating "Zombies" units without even realizing that we are)

**Comment by kaihendry** [comment]
Right now, the way the lambdas triggered from SQL work, is that a **response** must be made by MEFE, else the followup SQL is not run. https://github.com/unee-t/lambda2sns/blob/master/functions/simple/main.go#L196

If we change MEFE to trigger unit creation asynchronously, a LOT of changes and complexity needs to be introduced. MEFE would need a callback end point which it doesn't have right now. That callback would also probably need to trigger the [CREATE_UNIT](https://github.com/unee-t/lambda2sns/blob/master/functions/simple/main.go#L253) logic. This is not implemented and @nbiton would be in the best position to implement it.

Unit creation seems to run [as slow](https://github.com/unee-t/whyslow/blob/master/rds/seeslow.sh) as [8 seconds](https://s.natalian.org/2019-04-22/1555909765_2560x1440.png). If you rule out SQL optimization, I think it will be _very challenging_ to change the MEFE to an asynchronous flow given time & resources.

**Comment by franck-boullier** [comment]
> If you rule out SQL optimization,

yep: at this point I am ruling out SQL optimization. I'm not even sure that there is a way to make this routine faster. And in any case I don't see how this could be done in less than 3 to 6 months (best of the best case scenario IF we find a SQL guru that can help us do that).

> I think it will be very challenging to change the MEFE to an asynchronous flow

Do we have ANY other viable alternatives?

**Comment by franck-boullier** [comment]
> Unit creation seems to run as slow as 8 seconds. 

When triggering unit creation one at a time, unit creation takes 4 seconds or less. 
The below report was done on a batch creation of 5 units

```
"id_map"    "uneet_name"    "syst_created_datetime"    "uneet_created_datetime"    "creation_time"    "unee_t_mefe_unit_id"

"2"    "SG_SIN_LUM_37-04"    "2019-04-21 16:34:34"    "2019-04-21 16:35:07"    "00:00:33"    "GxcnNb1v5NL0BDSez"

"3"    "SG_SIN_LUM_37-05"    "2019-04-21 16:34:34"    "2019-04-21 16:35:06"    "00:00:32"    "hOkPEkM4hgSUteBlJ"

"17"    "SG_SIN_LUM_37-02"    "2019-04-21 17:17:36"    "2019-04-21 17:17:53"    "00:00:17"    "9Rord4Y0lEOe5j1GP"

"12"    "SG_SIN_LUM_36-01_02R"    "2019-04-21 16:59:08"    "2019-04-21 16:59:18"    "00:00:10"    "iO0e5q8Q7cfpBrsaM"

"18"    "SG_SIN_LUM_38-01"    "2019-04-21 17:21:23"    "2019-04-21 17:21:33"    "00:00:10"    "xZWGyWtzgQomlSwVG"

"13"    "SG_SIN_LUM_36-01_03R"    "2019-04-21 16:59:08"    "2019-04-21 16:59:17"    "00:00:09"    "RvvUi5xKABoXtqV4S"

"11"    "SG_SIN_LUM_36-01_01R"    "2019-04-21 16:59:08"    "2019-04-21 16:59:17"    "00:00:09"    "KCMMWdk6cjJwTqvKC"

"22"    "SG_SIN_LUM_38-05"    "2019-04-21 17:21:24"    "2019-04-21 17:21:33"    "00:00:09"    "3OfbaMZnm4aNAvNo6"

"20"    "SG_SIN_LUM_38-03"    "2019-04-21 17:21:23"    "2019-04-21 17:21:32"    "00:00:09"    "yBW2JE7opSA8v0N7N"

"15"    "SG_SIN_LUM_36-01"    "2019-04-21 17:17:36"    "2019-04-21 17:17:44"    "00:00:08"    "RGRS7TKZwtSWUzEo8"

"16"    "SG_SIN_LUM_37-01"    "2019-04-21 17:17:36"    "2019-04-21 17:17:44"    "00:00:08"    "P22L2ClUUb4ijwCHS"

"7"    "SG_SIN_OS_21-02"    "2019-04-21 16:54:21"    "2019-04-21 16:54:29"    "00:00:08"    "NgX9vNfeRuco1KPFZ"

"1"    "Lumiere - 1"    "2019-04-21 16:03:01"    "2019-04-21 16:03:08"    "00:00:07"    "TuvFnyrHch7YiCuXE"

"21"    "SG_SIN_LUM_38-04"    "2019-04-21 17:21:24"    "2019-04-21 17:21:31"    "00:00:07"    "zxNjYggOWICNOdlU3"

"19"    "SG_SIN_LUM_38-02"    "2019-04-21 17:21:23"    "2019-04-21 17:21:30"    "00:00:07"    "a5iZlRs6UXUESPRq8"

"10"    "SG_SIN_LUM_34-01_03M"    "2019-04-21 16:59:07"    "2019-04-21 16:59:12"    "00:00:05"    "aOQvHywFMh16hiPjr"

"4"    "SG_SIN_LUM_37-03"    "2019-04-21 16:43:46"    "2019-04-21 16:43:51"    "00:00:05"    "6TMWse0kxmDgEMte8"

"9"    "SG_SIN_LUM_34-01_02R"    "2019-04-21 16:59:07"    "2019-04-21 16:59:12"    "00:00:05"    "d8fG60KZXZCOhKGyR"

"8"    "SG_SIN_LUM_34-01_01M"    "2019-04-21 16:58:03"    "2019-04-21 16:58:07"    "00:00:04"    "OGHmWCaz4v6DsAEJa"

"14"    "SG_SIN_LUM_34-01"    "2019-04-21 17:17:36"    "2019-04-21 17:17:40"    "00:00:04"    "oh2R9w7qcbRUSGnRe"

"5"    "OS - 1"    "2019-04-21 16:51:26"    "2019-04-21 16:51:30"    "00:00:04"    "zDV8Ttgn4H7ICxADY"

"6"    "SG_SIN_OS_16-01"    "2019-04-21 16:54:21"    "2019-04-21 16:54:25"    "00:00:04"    "mSGSCfnIjuzJiXvdi"
```

Not sure where the 8 seconds benchmark is coming from but there is a high volatility to the speed of unit creation (from less than 4 secs to more than 33 sec) <--- this is unexplained and I'd like to get to the root cause of this difference (almost 1 order of magnitude for the same operation) <--- we are definitely missing something here

**Comment by kaihendry** [comment]
I've opened a support request for help profiling unit creation: https://console.aws.amazon.com/support/cases?region=ap-southeast-1#/6006523781/en

If Enterprise can call lambda sequentially, that would be a solution. I.e. create units in smaller batches to avoid timeouts when load is on **CALL `unit_create_with_dummy_users`**. Maybe we can put the messages on a queue and only allow lambda to process them one by one. Some re-architecting would need to happen, but this approach wouldn't require changes from MEFE.

**Comment by kaihendry** [comment]
On the dev environment I have tweaked alambda_simple which _might_ be enough. I.e. no need for queue.

<img src=https://s.natalian.org/2019-04-22/1555912452_2560x1440.png>

@franck-boullier Can you test this? If it works, I'll update prod. If it doesn't, I will implement the queue.

You might also need to run them as lambda_async and **not lambda_sync** in this case.

**Comment by kaihendry** [comment]
Today, we have:

* Unit creation `unit_create_with_dummy_users` taking >30s in the DEV environment
* On PROD `unit_create_with_dummy_users` is fast enough **not to appear in the slow_log** where long_query_time is 0.5s for all envs

Prod is running on 2x db.r4.large instances in a reader/writer configuration. Dev is on 1x db.r4.large.

Potential solutions:
* We split out CREATE_UNIT from [lambda2sns](https://github.com/unee-t/lambda2sns/blob/master/functions/simple/main.go#L96) and put it in the queue to ensure requests happen one by one (sequentially). Assumptions it appears to be fast enough when operating sequentially.
* we try make dev environment closer to prod. Cons: Expensive (2xr4.large!) and a little complex.
* We profile unit_create_with_dummy_users to try figure out why it's taking longer in one env and not another.

**Comment by franck-boullier** [comment]
The correct short term solution IMO:
- try make dev environment closer to prod. do NOT use 2xr4 large but smaller/cheaper instances instead (2 small at first and then see how this performs in the DEV).

Doing this we might realize that we might not need large instances in the prod too.

If this is not working then, we can look at how to split CREATE_UNIT.

**Comment by kaihendry** [comment]
In dev there is 2xdb.t2.medium setup like prod, but with lower instance types.

I am working on eliminating any other differences. I am having a [hard time simulating](https://stackoverflow.com/questions/55789373/run-a-benchmark-in-parallel-i-e-simulate-simultaneous-requests/55790771#55790771) the bulk tests you put on the Unit creation API though.

Sequentially they appear to take ~3s in dev & remember we can for sequential effectively by reducing concurrency to 1 for lambda2sns and lambda_async calls to it should be queued.

**Comment by kaihendry** [comment]
When a post times out, it's upto lambda2sns to trigger a retry.

If it fails again, the payload will enter the lamda2sns DLQ. We don't retry from DLQ **yet** since we first need to distinguish between payloads that are simply invalid.
