### ISSUE TITLE
Failure to connect to Lambda yields the wrong response code

### ISSUE THREAD

**Issue by nbiton** [unee-t/unit#14]
The following error was logged:
`failed [400] dial tcp 172.31.25.94:3306: connect: connection refused`

The expected response code in this scenario is 500 and not 400. Since it was 400, the retry logic did not allow for a another attempt.
This probably has nothing to do with the lambda code, but maybe with how it's defined in AWS?

**Comment by kaihendry** [comment]
Fixed for Unit. I need to apply the same logic to other lambdas like https://github.com/unee-t/unit/issues/14
