### ISSUE TITLE
Create the API to Disable a unit

### ISSUE THREAD

**Issue by franck-boullier** [unee-t/unit#4]
We to have an API which is able to trigger the script https://github.com/unee-t/unit/blob/master/sql/unit_disable_existing.sql

This is needed so that we can disable an existing unit in the MEFE.

**Comment by kaihendry** [comment]
What does [BZ product id for the unit](https://github.com/unee-t/unit/blob/f95debd81ad2e9f9113e73fc07feff3db9fb1030/sql/unit_disable_existing.sql#L18) map to?

Can I assume **mefe_unit_id**?

**Comment by franck-boullier** [comment]
> What does BZ product id for the unit map to?

The ID of the unit in the BZ database.
This is NOT the MEFE ID of the unit

**Comment by franck-boullier** [comment]
@kaihendry code should mention the BZ unit I'd and NOT the MEFE of for that

**Comment by kaihendry** [comment]
Can you please give an example of a BZ unit ID and where it comes from.

**Comment by franck-boullier** [comment]
> Can you please give an example of a BZ unit ID

4

>where it comes from

The Mongo Collection `unitMetaData`

**Comment by franck-boullier** [comment]
> where it comes from

For the purpose of the 'Disable Unit' function, this should come from whatever interface is calling your API and pass it to that API as the only variable you need.
